27.1. Playwright Network & API Request
Den-Zag/itHillelPlaywright pull request #6
Opened 2024-08-10 20:18 UTC by Den-Zag

2024-08-10 21:35 UTC, sttaran requested changes

2024-08-10 21:35 UTC, sttaran commented on tests/locators/hw27.spec.js
> +    await page.pause()
what are you trying to do here? Why your variable called `mockedCarBrands`? Why don't you assert value is being mocked on UI?

2024-08-10 21:35 UTC, sttaran commented on tests/locators/hw27.spec.js
> +    })
add one more negative scenario to finish this homework

2024-08-10 21:35 UTC, sttaran commented on tests/locators/hw27.spec.js
> +    expect(response.ok()).toBeFalsy()
check response body

2024-08-10 21:35 UTC, sttaran commented on tests/locators/hw27.spec.js
> +    expect(response.ok()).toBeFalsy()
use await expect(response).not.toBeOK();

2024-08-10 21:35 UTC, sttaran commented on tests/locators/hw27.spec.js
> +    expect(response.ok()).toBeFalsy()
https://playwright.dev/docs/api/class-apiresponseassertions#api-response-assertions-to-be-ok

2024-08-11 04:52 UTC, Den-Zag commented on tests/locators/hw27.spec.js
> +    await page.pause()
Я тут підміняю дані профіль юзера, як я розумію. 
Тут маєте на увазі, що потрібно змінити назву змінної, типу на "mockedUsersProfile"?

2024-08-11 11:49 UTC, sttaran requested changes

2024-08-11 11:49 UTC, sttaran commented on src/pageObjects/garagePage/GaragePage.js
> +      this.profilNameAndLastName = page.locator(".profile_name.display-4")
these elements are not parts of GaragePage

another page object should be created

2024-08-11 11:49 UTC, sttaran commented on tests/locators/hw27.spec.js
> +    expect(response.status()).toBe(404)
if you check status code you don't need this 
```expect(response).not.toBeOK()```

2024-08-11 20:25 UTC, sttaran approved these changes

2024-08-13 04:28 UTC, merged